/**
 * Created by denis on 29.02.16.
 */
// Other files are similar - we describe model (and relations too, for sure).
// And explicitly points to SQL table, already generated by django's ORM
module.exports = function(sequelize, DataTypes) {
  Message = sequelize.import(__dirname + '/message');
  var User = sequelize.define("User", {
    email: DataTypes.STRING,
    username: DataTypes.STRING
  }, {
    tableName: 'base_member',
    timestamps: false
  });
  User.hasMany(Message, {as: 'messages'});
  return User;
};