# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 21:20
from __future__ import unicode_literals

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160228_2110'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', base.models.MemberManager()),
            ],
        ),
    ]
